name: Check SemVer

on:
  push:
    branches: ['main']
    tags:
      - '*'
  workflow_dispatch:

permissions: {}

jobs:
  check-semver:
    permissions:
      contents: write

    concurrency:
      group: '${{ github.workflow }}'
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: jessehouwing/actions-semver-checker@1d5f1c217079bb5366ed9b12025fcece100f6bc5 # v2.1.0
        with:
          floating-versions-use: tags
          check-minor-version: error
          check-release-immutability: error
          ignore-preview-releases: true
          check-releases: error
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-fix: true
